import Foundation

/// One starter-set word that this POC video exposes the learner to.
/// Mirrors the JSON shape returned by `/api/v1/poc-videos`.
struct PocStarterWord: Codable, Identifiable, Hashable {
    let id: String
    let word: String
    let tr: String
    let occurrences: Int
}

/// A POC-flagged video the learner can pick from the home feed.
/// Aggregates over the video's healthy clips (those in the WPM 80-200 /
/// avg-sentence-length 3-12 band) so the card can show meaningful
/// difficulty signals.
struct PocVideo: Codable, Identifiable, Hashable {
    let id: String
    let youtubeVideoId: String
    let title: String
    let movieTitle: String
    let difficulty: String
    let wpm: Double?
    let a2Ratio: Double?
    let avgSentenceLen: Double?
    let clipCount: Int
    let totalLines: Int
    let taggedLines: Int
    let starterWords: [PocStarterWord]

    enum CodingKeys: String, CodingKey {
        case id, title, difficulty, wpm
        case youtubeVideoId   = "youtube_video_id"
        case movieTitle       = "movie_title"
        case a2Ratio          = "a2_ratio"
        case avgSentenceLen   = "avg_sentence_len"
        case clipCount        = "clip_count"
        case totalLines       = "total_lines"
        case taggedLines      = "tagged_lines"
        case starterWords     = "starter_words"
    }

    /// YouTube hosts a static thumbnail per video. We use `hqdefault.jpg`
    /// (480x360) because it's always generated by YouTube — `maxresdefault`
    /// only exists for HD uploads and 404s on older / non-HD videos,
    /// surfacing as a broken-image icon in the feed.
    var thumbnailURL: URL? {
        URL(string: "https://img.youtube.com/vi/\(youtubeVideoId)/hqdefault.jpg")
    }
}
