import Foundation

/// Manual translation bundle. Mirrors /i18n from the RN app.
struct Translations {
    let language: NativeLanguage
    let dict: [String: String]

    func t(_ key: String) -> String {
        dict[key] ?? Localization.en[key] ?? key
    }
}

enum Localization {

    static func bundle(for lang: NativeLanguage) -> Translations {
        switch lang {
        case .tr: return Translations(language: .tr, dict: tr)
        case .es: return Translations(language: .es, dict: es)
        case .ar: return Translations(language: .ar, dict: ar)
        case .zh: return Translations(language: .zh, dict: zh)
        case .pt: return Translations(language: .pt, dict: pt)
        case .en: return Translations(language: .en, dict: en)
        }
    }

    static let en: [String: String] = [
        // Tabs / general
        "learn": "Learn",
        "video": "Video",
        "vocabulary": "Vocabulary",
        "patterns": "Patterns",
        "scenes": "Scenes",
        "profile": "Profile",
        "words": "Words",
        "structures": "Structures",
        "dayStreak": "Day streak",
        "totalExperience": "Total experience",
        "nativeLanguage": "Native language",
        "continue": "Continue",
        "start": "Start",
        "next": "Next",
        "back": "Back",
        "done": "Done",
        "retry": "Retry",
        "loading": "Loading…",
        // Onboarding
        "welcome": "Welcome",
        "chooseLanguage": "Choose your native language",
        "whatsYourLevel": "What's your level?",
        "levelBeginner": "Beginner",
        "levelElementary": "Elementary",
        "levelIntermediate": "Intermediate",
        "whatsYourGoal": "Why are you learning?",
        "goalTravel": "Travel",
        "goalWork": "Work",
        "goalSchool": "School",
        "goalPersonal": "Personal growth",
        "dailyGoal": "Daily goal",
        "minutesPerDay": "minutes per day",
        "chooseDailyGoal": "How long each day?",
        "startLearning": "Start learning",
        // Home
        "goodMorning": "Good morning",
        "goodAfternoon": "Good afternoon",
        "goodEvening": "Good evening",
        "todaysPlan": "Today's plan",
        "continueLearning": "Continue learning",
        "recommendedForYou": "Recommended for you",
        "noCurriculum": "No lessons available",
        "errorLoading": "Couldn't load content",
        "tryAgain": "Try again",
        // Lesson
        "learnRules": "Learn",
        "studyVocab": "Vocabulary",
        "watchClips": "Watch",
        "practiceTest": "Test",
        "mastered": "Mastered",
        "startLesson": "Start lesson",
        "reviewLesson": "Review lesson",
        "examples": "Examples",
        "tip": "Tip",
        "dialogue": "Dialogue",
        "exercise": "Exercise",
        // Vocab
        "knownWords": "Known",
        "learningWords": "Learning",
        "toReview": "To review",
        "startReview": "Start review",
        // Player
        "skipIntro": "Skip intro",
        "playAgain": "Play again",
        "showTranslation": "Show translation",
        "hideTranslation": "Hide translation",
        // Profile
        "dailyGoalLabel": "Daily goal",
        "settings": "Settings",
        "about": "About",
        // Daily tasks
        "dailyTasksTitle": "Today's tasks",
        "dailyTasksSubtitle": "Small steps, big wins",
        "taskGrammar": "Grammar clip",
        "taskVocab": "Vocab review",
        "taskNew": "New lesson",
        "taskListening": "Listening"
    ]

    static let tr: [String: String] = [
        "learn": "Öğren",
        "video": "Video",
        "vocabulary": "Kelimeler",
        "patterns": "Kalıplar",
        "scenes": "Sahneler",
        "profile": "Profil",
        "words": "Kelime",
        "structures": "Yapı",
        "dayStreak": "Gün üst üste",
        "totalExperience": "Toplam deneyim",
        "nativeLanguage": "Ana dilin",
        "continue": "Devam",
        "start": "Başla",
        "next": "İleri",
        "back": "Geri",
        "done": "Tamam",
        "retry": "Tekrar dene",
        "loading": "Yükleniyor…",
        "welcome": "Hoş geldin",
        "chooseLanguage": "Ana dilini seç",
        "whatsYourLevel": "Seviyeniz nedir?",
        "levelBeginner": "Başlangıç",
        "levelElementary": "Temel",
        "levelIntermediate": "Orta",
        "whatsYourGoal": "Neden öğreniyorsun?",
        "goalTravel": "Seyahat",
        "goalWork": "İş",
        "goalSchool": "Okul",
        "goalPersonal": "Kendim için",
        "dailyGoal": "Günlük hedef",
        "minutesPerDay": "dakika / gün",
        "chooseDailyGoal": "Her gün ne kadar?",
        "startLearning": "Öğrenmeye başla",
        "goodMorning": "Günaydın",
        "goodAfternoon": "İyi günler",
        "goodEvening": "İyi akşamlar",
        "todaysPlan": "Bugünün planı",
        "continueLearning": "Öğrenmeye devam et",
        "recommendedForYou": "Sana önerilenler",
        "noCurriculum": "Henüz ders yok",
        "errorLoading": "İçerik yüklenemedi",
        "tryAgain": "Tekrar dene",
        "learnRules": "Öğren",
        "studyVocab": "Kelimeler",
        "watchClips": "İzle",
        "practiceTest": "Test",
        "mastered": "Tamamlandı",
        "startLesson": "Derse başla",
        "reviewLesson": "Dersi tekrarla",
        "examples": "Örnekler",
        "tip": "İpucu",
        "dialogue": "Diyalog",
        "exercise": "Alıştırma",
        "knownWords": "Bilinen",
        "learningWords": "Öğreniliyor",
        "toReview": "Tekrar",
        "startReview": "Tekrara başla",
        "skipIntro": "Girişi atla",
        "playAgain": "Yeniden oynat",
        "showTranslation": "Çeviriyi göster",
        "hideTranslation": "Çeviriyi gizle",
        "dailyGoalLabel": "Günlük hedef",
        "settings": "Ayarlar",
        "about": "Hakkında",
        "dailyTasksTitle": "Bugünün görevleri",
        "dailyTasksSubtitle": "Küçük adımlar, büyük kazanımlar",
        "taskGrammar": "Gramer klibi",
        "taskVocab": "Kelime tekrarı",
        "taskNew": "Yeni ders",
        "taskListening": "Dinleme"
    ]

    static let es: [String: String] = [
        "learn": "Aprender", "video": "Video", "vocabulary": "Vocabulario",
        "patterns": "Patrones",
        "scenes": "Escenas", "profile": "Perfil", "words": "Palabras",
        "structures": "Estructuras", "dayStreak": "Días seguidos",
        "totalExperience": "Experiencia total", "nativeLanguage": "Idioma nativo",
        "continue": "Continuar", "start": "Empezar", "next": "Siguiente",
        "back": "Atrás", "done": "Listo", "retry": "Reintentar", "loading": "Cargando…",
        "welcome": "Bienvenido", "chooseLanguage": "Elige tu idioma nativo",
        "whatsYourLevel": "¿Cuál es tu nivel?",
        "levelBeginner": "Principiante", "levelElementary": "Elemental", "levelIntermediate": "Intermedio",
        "whatsYourGoal": "¿Por qué estudias?",
        "goalTravel": "Viajar", "goalWork": "Trabajo", "goalSchool": "Estudios", "goalPersonal": "Crecimiento",
        "dailyGoal": "Meta diaria", "minutesPerDay": "minutos por día",
        "chooseDailyGoal": "¿Cuánto cada día?", "startLearning": "Empezar",
        "goodMorning": "Buenos días", "goodAfternoon": "Buenas tardes", "goodEvening": "Buenas noches",
        "todaysPlan": "Plan de hoy", "continueLearning": "Sigue aprendiendo",
        "recommendedForYou": "Recomendado para ti", "noCurriculum": "Sin lecciones",
        "errorLoading": "Error al cargar", "tryAgain": "Reintentar",
        "learnRules": "Aprende", "studyVocab": "Vocabulario", "watchClips": "Mira", "practiceTest": "Prueba",
        "mastered": "Dominado", "startLesson": "Empezar", "reviewLesson": "Repasar",
        "examples": "Ejemplos", "tip": "Consejo", "dialogue": "Diálogo", "exercise": "Ejercicio",
        "knownWords": "Conocidas", "learningWords": "Aprendiendo", "toReview": "Por revisar",
        "startReview": "Empezar repaso",
        "skipIntro": "Saltar intro", "playAgain": "Reproducir",
        "showTranslation": "Mostrar traducción", "hideTranslation": "Ocultar traducción",
        "dailyGoalLabel": "Meta diaria", "settings": "Ajustes", "about": "Acerca de",
        "dailyTasksTitle": "Tareas de hoy", "dailyTasksSubtitle": "Pasos pequeños, logros grandes",
        "taskGrammar": "Gramática", "taskVocab": "Vocabulario", "taskNew": "Nueva", "taskListening": "Escucha"
    ]

    static let ar: [String: String] = [
        "learn": "تعلم", "video": "فيديو", "vocabulary": "مفردات",
        "patterns": "أنماط",
        "scenes": "مشاهد", "profile": "الملف", "words": "كلمات", "structures": "قواعد",
        "dayStreak": "أيام متتالية", "totalExperience": "مجموع الخبرة", "nativeLanguage": "اللغة الأم",
        "continue": "متابعة", "start": "ابدأ", "next": "التالي", "back": "رجوع",
        "done": "تم", "retry": "حاول مجدداً", "loading": "جارٍ التحميل…",
        "welcome": "أهلاً", "chooseLanguage": "اختر لغتك الأم",
        "whatsYourLevel": "ما مستواك؟",
        "levelBeginner": "مبتدئ", "levelElementary": "أساسي", "levelIntermediate": "متوسط",
        "whatsYourGoal": "ما هدفك؟", "goalTravel": "سفر", "goalWork": "عمل",
        "goalSchool": "دراسة", "goalPersonal": "تطوير شخصي",
        "dailyGoal": "هدف يومي", "minutesPerDay": "دقيقة / يوم",
        "chooseDailyGoal": "كم كل يوم؟", "startLearning": "ابدأ التعلم",
        "goodMorning": "صباح الخير", "goodAfternoon": "مساء الخير", "goodEvening": "مساء الخير",
        "todaysPlan": "خطة اليوم", "continueLearning": "تابع التعلم",
        "recommendedForYou": "مقترح لك", "noCurriculum": "لا دروس بعد",
        "errorLoading": "خطأ في التحميل", "tryAgain": "حاول مجدداً",
        "learnRules": "تعلم", "studyVocab": "المفردات", "watchClips": "شاهد", "practiceTest": "اختبار",
        "mastered": "أتقنت", "startLesson": "ابدأ الدرس", "reviewLesson": "مراجعة الدرس",
        "examples": "أمثلة", "tip": "نصيحة", "dialogue": "حوار", "exercise": "تمرين",
        "knownWords": "معروف", "learningWords": "قيد التعلم", "toReview": "للمراجعة",
        "startReview": "ابدأ المراجعة",
        "skipIntro": "تخطَّ", "playAgain": "أعد التشغيل",
        "showTranslation": "إظهار الترجمة", "hideTranslation": "إخفاء الترجمة",
        "dailyGoalLabel": "الهدف اليومي", "settings": "الإعدادات", "about": "حول",
        "dailyTasksTitle": "مهام اليوم", "dailyTasksSubtitle": "خطوات صغيرة، إنجازات كبيرة",
        "taskGrammar": "قواعد", "taskVocab": "مفردات", "taskNew": "جديد", "taskListening": "استماع"
    ]

    static let zh: [String: String] = [
        "learn": "学习", "video": "视频", "vocabulary": "词汇",
        "patterns": "句型",
        "scenes": "场景", "profile": "个人", "words": "词汇", "structures": "结构",
        "dayStreak": "连续天数", "totalExperience": "总经验", "nativeLanguage": "母语",
        "continue": "继续", "start": "开始", "next": "下一步", "back": "返回",
        "done": "完成", "retry": "重试", "loading": "加载中…",
        "welcome": "欢迎", "chooseLanguage": "选择母语",
        "whatsYourLevel": "你的水平？",
        "levelBeginner": "入门", "levelElementary": "基础", "levelIntermediate": "中级",
        "whatsYourGoal": "学习目标？",
        "goalTravel": "旅行", "goalWork": "工作", "goalSchool": "学业", "goalPersonal": "个人成长",
        "dailyGoal": "每日目标", "minutesPerDay": "分钟 / 天",
        "chooseDailyGoal": "每天多少？", "startLearning": "开始学习",
        "goodMorning": "早上好", "goodAfternoon": "下午好", "goodEvening": "晚上好",
        "todaysPlan": "今日计划", "continueLearning": "继续学习",
        "recommendedForYou": "为你推荐", "noCurriculum": "暂无课程",
        "errorLoading": "加载失败", "tryAgain": "重试",
        "learnRules": "学习", "studyVocab": "词汇", "watchClips": "观看", "practiceTest": "测试",
        "mastered": "已掌握", "startLesson": "开始课程", "reviewLesson": "复习",
        "examples": "例句", "tip": "提示", "dialogue": "对话", "exercise": "练习",
        "knownWords": "已知", "learningWords": "学习中", "toReview": "待复习",
        "startReview": "开始复习",
        "skipIntro": "跳过", "playAgain": "再播一次",
        "showTranslation": "显示翻译", "hideTranslation": "隐藏翻译",
        "dailyGoalLabel": "每日目标", "settings": "设置", "about": "关于",
        "dailyTasksTitle": "今日任务", "dailyTasksSubtitle": "小步前进，大有收获",
        "taskGrammar": "语法", "taskVocab": "词汇", "taskNew": "新内容", "taskListening": "听力"
    ]

    static let pt: [String: String] = [
        "learn": "Aprender", "video": "Vídeo", "vocabulary": "Vocabulário",
        "patterns": "Padrões",
        "scenes": "Cenas", "profile": "Perfil", "words": "Palavras", "structures": "Estruturas",
        "dayStreak": "Dias seguidos", "totalExperience": "Experiência total", "nativeLanguage": "Idioma nativo",
        "continue": "Continuar", "start": "Começar", "next": "Próximo", "back": "Voltar",
        "done": "Pronto", "retry": "Tentar novamente", "loading": "Carregando…",
        "welcome": "Bem-vindo", "chooseLanguage": "Escolha seu idioma nativo",
        "whatsYourLevel": "Qual seu nível?",
        "levelBeginner": "Iniciante", "levelElementary": "Básico", "levelIntermediate": "Intermediário",
        "whatsYourGoal": "Por que estuda?",
        "goalTravel": "Viagem", "goalWork": "Trabalho", "goalSchool": "Escola", "goalPersonal": "Pessoal",
        "dailyGoal": "Meta diária", "minutesPerDay": "minutos / dia",
        "chooseDailyGoal": "Quanto por dia?", "startLearning": "Começar",
        "goodMorning": "Bom dia", "goodAfternoon": "Boa tarde", "goodEvening": "Boa noite",
        "todaysPlan": "Plano de hoje", "continueLearning": "Continue aprendendo",
        "recommendedForYou": "Para você", "noCurriculum": "Sem lições",
        "errorLoading": "Falha ao carregar", "tryAgain": "Tentar novamente",
        "learnRules": "Aprender", "studyVocab": "Vocabulário", "watchClips": "Assista", "practiceTest": "Teste",
        "mastered": "Dominado", "startLesson": "Começar", "reviewLesson": "Revisar",
        "examples": "Exemplos", "tip": "Dica", "dialogue": "Diálogo", "exercise": "Exercício",
        "knownWords": "Conhecidas", "learningWords": "Aprendendo", "toReview": "Revisar",
        "startReview": "Começar revisão",
        "skipIntro": "Pular", "playAgain": "Repetir",
        "showTranslation": "Mostrar tradução", "hideTranslation": "Ocultar tradução",
        "dailyGoalLabel": "Meta diária", "settings": "Ajustes", "about": "Sobre",
        "dailyTasksTitle": "Tarefas de hoje", "dailyTasksSubtitle": "Passos pequenos, grandes ganhos",
        "taskGrammar": "Gramática", "taskVocab": "Vocabulário", "taskNew": "Novo", "taskListening": "Escuta"
    ]
}
